export const $body = document.body
// start
export const $start = $body.querySelector('#start')
export const $continueLink = $start.querySelector('#continueLink')
export const $botLink = $start.querySelector('#botLink')
export const $friendLink = $start.querySelector('#friendLink')
export const $statsLink = $start.querySelector('#statsLink')
// stats
export const $stats = $body.querySelector('#stats')
export const $totalWins = $stats.querySelector('#totalWins')
export const $totalLosses = $stats.querySelector('#totalLosses')
// size
export const $size = $body.querySelector('#size')
export const $positionLink = $size.querySelector('#positionLink')
export const $fieldOnSizeSection = $size.querySelector('#fieldOnSizeSection')
export const $canvasOnSizeSection = $fieldOnSizeSection.querySelector('canvas')
export const $fieldRange = $size.querySelector('#fieldRange')
export const $fieldSizeLabel = $size.querySelector('#fieldSizeLabel')
export const $shipFour = $size.querySelector('#shipFour')
export const $shipThree = $size.querySelector('#shipThree')
export const $shipTwo = $size.querySelector('#shipTwo')
export const $shipOne = $size.querySelector('#shipOne')
// position
export const $position = $body.querySelector('#position')
export const $battleLink = $position.querySelector('#battleLink')
export const $fieldOnPositionSection = $position.querySelector('#fieldOnPositionSection')
export const $positionShipList = $position.querySelector('#positionShipList')
export const $playerChangeName = $position.querySelector('#playerChangeName')
export const $changePlayerPosition = $position.querySelector('#changePlayerPosition')
// battle
export const $battle = $body.querySelector('#battle')
export const $logOffLink = $battle.querySelector('#logOffLink')
export const $changeLink = $battle.querySelector('#changeLink')
export const $enemyField = $battle.querySelector('#enemyField')
export const $unionField = $battle.querySelector('#unionField')
export const $playerSavedName = $battle.querySelector('#playerSavedName')
