export const navList = Array.from(document.querySelectorAll('[data-nav="transition"]'))
export const fieldList = Array.from(document.querySelectorAll('[data-canvas="field"]'))
export const shipFormList = Array.from(document.querySelectorAll('[data-form="ship"]'))
export const statsInpuList = Array.from(document.querySelectorAll('[data-input="stats"]'))
export const playerNameList = Array.from(document.querySelectorAll('[data-input="playerName"]'))
